testComment
veronikatimkina/first-test-pr-jb pull request #49
Opened 2020-09-01 14:06 UTC by testaccount120

2020-10-12 17:27 UTC, veronikatimkina approved these changes
approve pr from vt

2020-11-13 14:54 UTC, testaccount120 commented
![2020-10-22_18-06-42](https://user-images.githubusercontent.com/63915539/99085441-3c9d3a00-25d9-11eb-9015-866df14d75d2.png)

2020-11-18 17:57 UTC, veronikatimkina commented
варварвар

2020-11-18 17:57 UTC, veronikatimkina commented
пиапиапиапи

2020-11-18 17:58 UTC, veronikatimkina commented
ыпвапварвар

2020-11-18 17:58 UTC, veronikatimkina commented
апвапвапва

2020-12-03 15:45 UTC, veronikatimkina approved these changes

2020-12-03 15:45 UTC, veronikatimkina commented on src/main/java/Main.java
> +        earlBio.add(str3);
test multiline

2020-12-04 10:12 UTC, veronikatimkina requested changes

2020-12-04 10:28 UTC, veronikatimkina commented on src/main/java/Main.java
> +        String str3 = "I love Java";
reply

2020-12-04 12:05 UTC, veronikatimkina requested changes

2020-12-04 12:05 UTC, veronikatimkina commented on src/main/java/Newclass.java
> +    }
bzzzz

2020-12-04 12:05 UTC, veronikatimkina commented on src/main/java/Main.java
>  }
dggrgerg

2020-12-04 13:07 UTC, veronikatimkina commented on src/main/java/TestaccClass.java
fff

2020-12-04 13:07 UTC, veronikatimkina commented on src/main/java/TestaccClass.java
>      }
fff

2020-12-04 13:23 UTC, veronikatimkina commented on src/main/java/TestaccClass.java
>      }
hhh

2020-12-04 13:44 UTC, veronikatimkina commented on src/main/java/Main.java
dvdvdv

2020-12-04 14:52 UTC, veronikatimkina commented on src/main/java/Main.java
dccdcvfv

2020-12-04 16:21 UTC, veronikatimkina commented
alala

2020-12-04 17:48 UTC, veronikatimkina approved these changes

2020-12-04 17:48 UTC, veronikatimkina commented on src/main/java/Main.java
> +        String str2 = "My name is Earl";
ehrhhr

2020-12-04 17:48 UTC, veronikatimkina commented on src/main/java/Main.java
> +        earlBio.add(str1);
a

2020-12-04 17:48 UTC, veronikatimkina commented on src/main/java/SomeClass.java
> +}
sssssssss

2020-12-04 17:48 UTC, veronikatimkina commented on src/main/java/Newclass.java
> +
gbhghdghdfghdghh

2020-12-17 14:53 UTC, nika-qa commented
![2020-06-09-19-16-25](https://user-images.githubusercontent.com/75311384/102503442-c89af980-4090-11eb-9dd0-ca447a34c9c4.png)

2020-12-17 15:08 UTC, nika-qa reviewed
![2020-07-20_17-41-52](https://user-images.githubusercontent.com/75311384/102505284-db163280-4092-11eb-8e61-345e3c590482.png)

2020-12-17 15:09 UTC, nika-qa commented
![2020-12-15_16-50-05](https://user-images.githubusercontent.com/75311384/102505370-f41ee380-4092-11eb-9a80-146af0bfbc62.png)

2020-12-18 10:15 UTC, nika-qa commented
test

2021-01-21 15:18 UTC, veronikatimkina requested changes

2021-01-21 15:18 UTC, veronikatimkina commented on src/main/java/pack/Class11.java
>  public class Class11 {
кпукпкуп

2021-01-28 12:12 UTC, veronikatimkina commented
errgerger

2021-03-12 15:43 UTC, veronikatimkina commented
hterherherh

2021-12-22 17:33 UTC, merged