abranch
veronikatimkina/first-test-pr-jb pull request #54
Opened 2020-12-09 20:19 UTC by veronikatimkina

2020-12-09 20:31 UTC, veronikatimkina commented on src/TestBr.java
> +        System.out.println();
from ide

2020-12-09 20:32 UTC, nika-qa reviewed
review comment

2020-12-09 20:32 UTC, nika-qa commented on src/TestBr.java
> +        System.out.println();
comment from web

2020-12-09 20:34 UTC, nika-qa commented on src/TestBr.java
> +        System.out.println();
reply from web

2020-12-09 20:44 UTC, nika-qa requested changes

2020-12-09 20:44 UTC, nika-qa commented on src/TestBr.java
> +        System.out.println();
from IDE

2020-12-09 20:45 UTC, veronikatimkina commented on src/main/java/pack/Test.java
>  package main.java.pack;
from web

2021-01-14 09:38 UTC, veronikatimkina commented on src/main/java/pack/Test.java
start

2021-03-12 10:04 UTC, closed without merging